version: '3.7'

services:
  cites:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver_plus", "0.0.0.0:8000"]
    volumes:
      - './:/usr/src/app'
    ports:
      - 8000:8000