version: '3.7'

services:
  cites:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - './:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - DB_HOST=cites_db
      - DB_NAME=cites
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    depends_on:
      - cites_db
  cites_db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cites
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres